# --- # Configuration file

keys:
  esc_key: 1048603
  quit_key: 113
  safe_key: 115
  next_key: 1048686
  left_key: 1113937
  right_key: 1113939
  down_key: 1113940
  up_key: 1113938
  enter_key: 1048586

joiner:
  left_video_start_frame: 0
  right_video_start_frame: 6
  point_selection_mode: 0
  left_video_top_left_x: 882
  left_video_top_right_x: 1895
  left_video_bottom_left_x: 36
  left_video_bottom_right_x: 1891
  left_video_top_left_y: 319
  left_video_top_right_y: 362
  left_video_bottom_left_y: 609
  left_video_bottom_right_y: 800
  right_video_top_left_x: 66
  right_video_top_right_x: 1014
  right_video_bottom_left_x: 140
  right_video_bottom_right_x: 1833
  right_video_top_left_y: 481
  right_video_top_right_y: 424
  right_video_bottom_left_y: 889
  right_video_bottom_right_y: 676
  video_top_left_x: 7
  video_top_right_x: 3655
  video_bottom_left_x: 7
  video_bottom_right_x: 3655
  video_top_left_y: 317
  video_top_right_y: 317
  video_bottom_left_y: 880
  video_bottom_right_y: 880
  enable_output_video_crop: 1
  sync_mode: 0
  left_timecode: 01:24:07.0
  right_timecode: 01:24:07.6
  enable_drop_frame: 1
  frame_rate: 29.97
  start_frame: 576
  stop_frame: 776
  frame2skip: 20
  enable_color_balance: 1
  enable_s_color_correction: 0
  enable_v_color_correction: 0
  color_correction_video_reference: left
  enable_color_region_selection: 0
  stitch_mode: 7
  divide_images: 0
  try_use_gpu: 1
  enable_top_corners_correction: 0
  left_top_corner_correction: 0
  right_top_corner_correction: 0
